services:

  postgres:
    image: postgres:16-alpine
    container_name: k0soa-postgres
    environment:
      POSTGRES_DB: k0_soa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: k0soa-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/k0_soa_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      NASA_DONKI_API_KEY: ${NASA_DONKI_API_KEY:-DEMO_KEY}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
