spring.application.name=k0-soa
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/k0_soa_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# NASA DONKI
nasa.donki.api-key=DEMO_KEY
nasa.donki.base-url=https://api.nasa.gov/DONKI
